controllers:
    resource: ../src/Controller/
    type: annotation

index:
    path: /
    controller: App\Controller\BaseController::index

comment_delete:
    path:       /article/comment/{$id}/delete
    controller: App\Controller\ArticleController::deleteComment
    methods:    POST
