controllers:
    resource: ../src/Controller/
    type: annotation

index:
    path: /
    controller: App\Controller\BaseController::index

show_hide_comment:
    path:       /article/comment/{$id}/showHide
    controller: App\Controller\ArticleController::showHideComment
    methods:    POST

delete_comment:
    path:       /article/comment/{$id}/delete
    controller: App\Controller\ArticleController::deleteComment
    methods:    POST
