controllers:
    resource: ../src/Controller/
    type: annotation

index:
    path: /
    controller: App\Controller\BaseController::index

comment_show:
    path:       /article/comments
    controller: App\Controller\CommentController::show
    methods:    GET
